backend:
  name: github
  repo: platform-kit/hellowork

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - label: "Content Editor"
    name: "pages"
    files:
      - label: "Portfolio"
        name: "about"
        file: "static/data.json"
        fields:          
          - label: Your Identity
            name: identity
            widget: object
            fields:              
              - {label: Name, name: name, widget: string}
              - {label: Full Name, name: fullName, widget: string}
              - {label: Initials, name: initials, widget: string}
              - {label: Image, name: avatar, widget: image}
          - label: Your Links
            name: links
            widget: object
            fields:              
              - {label: email, name: email, widget: string}
              - {label: resume, name: resume, widget: string}
              - {label: twitter, name: twitter, widget: string}
              - {label: instagram, name: instagram, widget: image}
          - label: Hero Section
            name: hero
            widget: object
            fields:              
              - {label: Headline, name: headline, widget: string}
          - label: Background Images
            name: backgroundImages
            widget: list
            field: {label: Image, name: image, widget: string}                          
          - label: Testimonials
            name: testimonials
            widget: object            
            fields:                         
              - {label: Image, name: image, widget: string}
          - label: Projects
            name: projects
            widget: list
            minimize_collapsed: true
            add_to_top: true
            summary: '{{fields.title}}'
            fields:                         
              - {label: ID, name: id, widget: string, unique: true}
              - {label: Title, name: title, widget: string}
              - {label: Tags, name: tags, widget: list}
              - {label: Description, name: description, widget: text}
              - {label: Image URL, name: thumbnail, widget: string}
              - {label: Video URL, name: video, widget: string}